backend:
    name: git-gateway
    branch: master
media_folder: src/media
public_folder: /media
collections:
    - name: post
      label: Post
      folder: src/posts
      create: true
      fields:
          - { name: title, label: Title, widget: string }
          - { name: layout, label: Layout, widget: hidden, default: post-layout.njk }
          - { name: body, label: Body, widget: markdown }
